# Generated by Django 4.2.6 on 2023-10-26 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('Income', models.IntegerField(blank=True, null=True)),
                ('Poverty_line', models.CharField(blank=True, max_length=100, null=True)),
                ('Disability', models.BooleanField(default=False)),
                ('Reservation', models.CharField(blank=True, max_length=100, null=True)),
                ('Aadhar_Number', models.IntegerField(blank=True, null=True)),
                ('Contact', models.IntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Profile_Image', models.ImageField(blank=True, null=True, upload_to='users/profile_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
