# Generated by Django 4.2.6 on 2023-10-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledb',
            name='Profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
